[project]
name = "sklearn-churn-predict-lambda"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zhf", email = "541099040@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
    "scikit-learn==1.6.1",
]

[project.scripts]
sklearn-churn-predict-lambda = "sklearn_churn_predict_lambda:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
