[project]
name = "ml-project-uv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "zhf", email = "541099040@qq.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.141.1",
    "pandas>=3.0.5",
    "requests>=2.34.2",
    "scikit-learn==1.6.1",
    "uvicorn>=0.52.4",
]

[project.scripts]
ml-project-uv = "ml_project_uv:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
